name: Protoc Build

on:
  workflow_call:

jobs:
  build:
    name: Protoc Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Protoc
        run: |
          sudo apt install -y protobuf-compiler

      - name: Compile and Test
        run: sh run_protocol_compilers.sh
  build-scala:
    name: ScalaPB Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup SBT
        run: |
          mkdir -p $HOME/bin/sbt
          set -eux && curl --fail --silent --location --retry 3 https://github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.tgz | gunzip | tar x -C $HOME/bin/sbt
          echo "$HOME/bin/sbt" >> $GITHUB_PATH

      - name: Compile and Test
        run: sbt +publishLocal
        working-directory: build/scala
  build-dart:
    name: Dart Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Setup Dart protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          dart pub global activate protoc_plugin

      - name: Compile and Test
        run: |
          ./compile_protos.sh
          dart pub get
          dart analyze
          dart test
        working-directory: build/dart
